name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: "15.4" }
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test
